"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Search, ShoppingCart, ArrowRight } from "lucide-react";
import { apiFetch } from "@/lib/api";
import { formatINR } from "@/lib/format";

type Row={id:number;customer_name:string|null;customer_email:string|null;customer_phone:string|null;status:string;line_count:number;item_count:number;cart_value:number;updated_at:string;last_item_activity:string|null};
export default function AdminCartsPage(){
 const [rows,setRows]=useState<Row[]>([]); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{try{setLoading(true);setError("");const q=search.trim()?`?search=${encodeURIComponent(search.trim())}`:"";const r=await apiFetch(`/admin/carts${q}`);const j=await r.json();if(!r.ok)throw new Error(j?.message||"Unable to load carts.");setRows(Array.isArray(j?.data)?j.data:[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load carts.");}finally{setLoading(false)}},[search]);
 useEffect(()=>{const t=setTimeout(()=>void load(),250);return()=>clearTimeout(t)},[load]);
 return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-gray-900">Customer Carts</h1><p className="mt-1 text-sm text-gray-500">See active shopping intent, customer phone details and cart value from one place.</p></div>
 <div className="rounded-xl border border-gray-200 bg-white p-4"><div className="relative max-w-xl"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer, phone or email..." className="w-full rounded-lg border border-gray-300 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-gray-600"/></div></div>
 {error&&<div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <div className="overflow-hidden rounded-xl border border-gray-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[900px]"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Phone</th><th className="px-5 py-3">Items</th><th className="px-5 py-3">Cart value</th><th className="px-5 py-3">Status</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-gray-100">{loading?<tr><td colSpan={6} className="px-5 py-12 text-center text-sm text-gray-500">Loading carts...</td></tr>:rows.length===0?<tr><td colSpan={6} className="px-5 py-14 text-center"><ShoppingCart className="mx-auto text-gray-300"/><p className="mt-2 text-sm text-gray-500">No carts found.</p></td></tr>:rows.map(row=><tr key={row.id} className="hover:bg-gray-50"><td className="px-5 py-4"><p className="font-medium text-gray-900">{row.customer_name||"Guest"}</p><p className="text-xs text-gray-500">{row.customer_email||"No email"}</p></td><td className="px-5 py-4 text-sm text-gray-700">{row.customer_phone||"—"}</td><td className="px-5 py-4 text-sm text-gray-700">{row.item_count} item{row.item_count===1?"":"s"} · {row.line_count} line{row.line_count===1?"":"s"}</td><td className="px-5 py-4 font-medium">{formatINR(row.cart_value)}</td><td className="px-5 py-4"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-medium capitalize text-emerald-700">{row.status||"active"}</span></td><td className="px-5 py-4 text-right"><Link href={`/admin/carts/${row.id}`} className="inline-flex items-center gap-1 text-sm font-semibold text-gray-800">View <ArrowRight size={15}/></Link></td></tr>)}</tbody></table></div></div></div>
}
