"use client";

export type AdminSize = { id:number; name:string; display_name?:string|null };
export type AdminColor = { id:number; name:string; display_name?:string|null; hex_code?:string|null };
export type VariantDraft = { size_id:number; color_id:number; sku:string; mrp:string; selling_price:string; quantity:string; low_stock_limit:string; status:string };

type Props={sizes:AdminSize[];colors:AdminColor[];selectedSizeIds:number[];selectedColorIds:number[];variants:VariantDraft[];onToggleSize:(id:number)=>void;onToggleColor:(id:number)=>void;onVariantChange:(index:number,field:keyof VariantDraft,value:string)=>void};

export default function VariantMatrixEditor({sizes,colors,selectedSizeIds,selectedColorIds,variants,onToggleSize,onToggleColor,onVariantChange}:Props){
 return <section className="rounded-xl border border-gray-200 bg-white p-6">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-semibold text-gray-900">Sizes, Colors & Variants</h2><p className="mt-1 text-sm text-gray-500">Select at least one size and one color. Every selected size × color combination is generated automatically.</p></div><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold text-gray-600">{variants.length} variant{variants.length===1?"":"s"}</span></div>
  <div className="mt-6 grid gap-6 lg:grid-cols-2">
   <div><p className="mb-3 text-sm font-medium text-gray-700">Available sizes *</p><div className="flex flex-wrap gap-2">{sizes.map(size=>{const active=selectedSizeIds.includes(size.id);return <button type="button" key={size.id} onClick={()=>onToggleSize(size.id)} className={`rounded-lg border px-4 py-2 text-sm font-medium transition ${active?"border-gray-900 bg-gray-900 text-white":"border-gray-300 bg-white text-gray-700 hover:border-gray-500"}`}>{size.display_name||size.name}</button>})}</div>{sizes.length===0&&<p className="text-sm text-amber-700">Create an active size first.</p>}</div>
   <div><p className="mb-3 text-sm font-medium text-gray-700">Available colors *</p><div className="flex flex-wrap gap-2">{colors.map(color=>{const active=selectedColorIds.includes(color.id);return <button type="button" key={color.id} onClick={()=>onToggleColor(color.id)} className={`flex items-center gap-2 rounded-lg border px-4 py-2 text-sm font-medium transition ${active?"border-gray-900 bg-gray-900 text-white":"border-gray-300 bg-white text-gray-700 hover:border-gray-500"}`}>{color.hex_code&&<span className="h-4 w-4 rounded-full border border-black/10" style={{backgroundColor:color.hex_code}}/>}{color.display_name||color.name}</button>})}</div>{colors.length===0&&<p className="text-sm text-amber-700">Create an active color first.</p>}</div>
  </div>
  {variants.length>0&&<div className="mt-7 overflow-x-auto rounded-xl border border-gray-200"><table className="w-full min-w-[980px]"><thead className="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr><th className="px-3 py-3">Size</th><th className="px-3 py-3">Color</th><th className="px-3 py-3">SKU *</th><th className="px-3 py-3">MRP *</th><th className="px-3 py-3">Selling *</th><th className="px-3 py-3">Stock</th><th className="px-3 py-3">Low stock</th></tr></thead><tbody className="divide-y divide-gray-100">{variants.map((v,i)=>{const size=sizes.find(x=>x.id===v.size_id);const color=colors.find(x=>x.id===v.color_id);return <tr key={`${v.size_id}:${v.color_id}`}><td className="px-3 py-3 text-sm font-medium">{size?.display_name||size?.name}</td><td className="px-3 py-3"><span className="flex items-center gap-2 text-sm">{color?.hex_code&&<span className="h-4 w-4 rounded-full border" style={{backgroundColor:color.hex_code}}/>}{color?.display_name||color?.name}</span></td>{(["sku","mrp","selling_price","quantity","low_stock_limit"] as (keyof VariantDraft)[]).map(field=><td key={field} className="px-2 py-3"><input type={field==="sku"?"text":"number"} min={field==="sku"?undefined:"0"} step={field==="mrp"||field==="selling_price"?"0.01":undefined} value={v[field]} onChange={e=>onVariantChange(i,field,e.target.value)} placeholder={field==="sku"?"SKU":"0"} className={`${field==="sku"?"w-40":"w-28"} rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none focus:border-gray-600`}/></td>)}</tr>})}</tbody></table></div>}
 </section>
}
