"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, RotateCcw } from "lucide-react";
import { customerApiFetch } from "@/lib/customerApi";

type ReturnRow={id:number;order_number:string;reason:string;status:string;refund_status:string;refund_amount:string;created_at:string};
export default function AccountReturnsPage(){const [rows,setRows]=useState<ReturnRow[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const r=await customerApiFetch('/customer/returns');const j=await r.json();if(r.status===401){location.href='/login';return;}if(!r.ok)throw new Error(j?.message||'Unable to load returns.');setRows(Array.isArray(j?.data)?j.data:[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load returns.');}finally{setLoading(false);}})();},[]);
 return <main className="min-h-screen bg-gray-50 px-4 py-10"><div className="mx-auto max-w-5xl"><Link href="/account" className="inline-flex items-center gap-2 text-sm text-gray-600"><ArrowLeft size={16}/> My Account</Link><div className="mt-5 flex items-center gap-3"><div className="rounded-xl bg-[#f8f1e5] p-3 text-[#8f0828]"><RotateCcw size={20}/></div><div><h1 className="text-3xl font-semibold text-gray-900">Returns & Refunds</h1><p className="mt-1 text-sm text-gray-500">Track requests submitted for delivered purchases.</p></div></div>{error&&<div className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="mt-6 overflow-hidden rounded-2xl border border-gray-200 bg-white">{loading?<div className="p-8 text-sm text-gray-500">Loading...</div>:rows.length===0?<div className="p-12 text-center text-sm text-gray-500">No return requests yet.</div>:<div className="divide-y divide-gray-100">{rows.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-semibold text-gray-900">Return #{r.id} · Order {r.order_number}</p><p className="mt-1 text-sm text-gray-500">{r.reason.replaceAll('_',' ')} · Refund ₹{Number(r.refund_amount||0).toFixed(2)}</p></div><span className="rounded-full bg-gray-100 px-3 py-1.5 text-xs font-semibold capitalize text-gray-700">{r.status}</span></div>)}</div>}</div></div></main>}
