import { Router } from "express";
import * as auth from "../controllers/customer/auth.controller.js";
import * as profile from "../controllers/customer/profile.controller.js";
import * as address from "../controllers/customer/address.controller.js";
import * as cart from "../controllers/customer/cart.controller.js";
import * as wishlist from "../controllers/customer/wishlist.controller.js";
import * as order from "../controllers/customer/order.controller.js";
import * as coupon from "../controllers/customer/coupon.controller.js";
import * as shipping from "../controllers/customer/shipping.controller.js";
import * as review from "../controllers/customer/review.controller.js";
import { auth as guard } from "../middleware/auth.js";
import { download as downloadInvoice } from "../controllers/customer/invoice.controller.js";
import * as notification from "../controllers/customer/notification.controller.js";
import * as password from "../controllers/customer/password.controller.js";
import * as returns from "../controllers/customer/return.controller.js";
const r = Router();
r.post("/register", auth.register);
r.post("/login", auth.login);
r.post("/forgot-password", password.forgot);
r.post("/reset-password", password.reset);
r.use(guard("customer"));
r.get("/me", auth.me);
r.post("/logout", auth.logout);
r.get("/profile", profile.show);
r.put("/profile", profile.update);
r.put("/profile/password", profile.changePassword);
r.get("/addresses", address.index);
r.post("/addresses", address.store);
r.get("/addresses/:id", address.show);
r.put("/addresses/:id", address.update);
r.delete("/addresses/:id", address.destroy);
r.put("/addresses/:id/default", address.setDefault);
r.get("/cart", cart.index);
r.post("/cart/items", cart.store);
r.put("/cart/items/:id", cart.update);
r.delete("/cart/items/:id", cart.destroy);
r.delete("/cart", cart.clear);
r.get("/orders", order.index);
r.post("/orders", order.store);
r.get("/orders/:id", order.show);
r.post("/orders/:id/cancel", order.cancel);
r.post("/orders/:id/reorder", order.reorder);
r.get("/returns", returns.index);
r.post("/returns", returns.store);
r.get("/returns/:id", returns.show);
r.get("/notifications", notification.index);
r.put("/notifications/:id/read", notification.read);
r.put("/notifications/read-all", notification.readAll);
r.get("/wishlist", wishlist.index);
r.post("/wishlist", wishlist.store);
r.get("/wishlist/check/:product", wishlist.check);
r.delete("/wishlist/:id", wishlist.destroy);
r.post("/coupons/validate", coupon.validateCoupon);
r.get("/shipping/quote", shipping.quote);
r.post("/products/:product/reviews", review.store);
r.get("/products/:product/reviews/mine", review.mine);
r.get("/orders/:id/invoice", downloadInvoice);
export default r;
