"use client";
import { FormEvent, useEffect, useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";
import { apiFetch } from "@/lib/api";

type Material={id:number;name:string;status:string;created_at:string|null};
export default function MaterialsPage(){const [rows,setRows]=useState<Material[]>([]);const [name,setName]=useState('');const [status,setStatus]=useState('active');const [editing,setEditing]=useState<number|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 async function load(){try{setLoading(true);const r=await apiFetch('/admin/materials');const j=await r.json();if(!r.ok)throw new Error(j?.message||'Unable to load materials.');setRows(Array.isArray(j?.data)?j.data:[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load materials.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 function reset(){setEditing(null);setName('');setStatus('active');}
 function edit(row:Material){setEditing(row.id);setName(row.name);setStatus(row.status);}
 async function submit(e:FormEvent){e.preventDefault();if(!name.trim())return;try{setSaving(true);const r=await apiFetch(editing?`/admin/materials/${editing}`:'/admin/materials',{method:editing?'PUT':'POST',body:JSON.stringify({name,status})});const j=await r.json();if(!r.ok)throw new Error(j?.message||'Unable to save material.');reset();void load();}catch(e){setError(e instanceof Error?e.message:'Unable to save material.');}finally{setSaving(false);}}
 async function remove(id:number){if(!confirm('Delete this material?'))return;const r=await apiFetch(`/admin/materials/${id}`,{method:'DELETE'});const j=await r.json();if(!r.ok){setError(j?.message||'Unable to delete material.');return;}void load();}
 return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#c9a227]">Catalog</p><h1 className="mt-2 text-3xl font-semibold text-gray-900">Materials</h1><p className="mt-1 text-sm text-gray-500">Manage material options used by your catalog.</p></div>{editing&&<button onClick={reset} className="inline-flex items-center gap-2 rounded-lg border border-gray-200 bg-white px-4 py-2 text-sm font-semibold"><X size={16}/> Cancel edit</button>}</div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<form onSubmit={submit} className="mt-6 flex flex-col gap-3 rounded-2xl border border-gray-200 bg-white p-5 sm:flex-row"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Material name" className="flex-1 rounded-lg border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#c9a227]"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border border-gray-200 px-3 py-3 text-sm"><option value="active">Active</option><option value="inactive">Inactive</option></select><button disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-lg bg-gray-900 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{editing?<Pencil size={16}/>:<Plus size={16}/>} {saving?'Saving...':editing?'Update':'Add material'}</button></form><div className="mt-6 overflow-hidden rounded-2xl border border-gray-200 bg-white">{loading?<div className="p-8 text-sm text-gray-500">Loading...</div>:rows.length===0?<div className="p-12 text-center text-sm text-gray-500">No materials yet.</div>:<div className="divide-y divide-gray-100">{rows.map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-semibold text-gray-900">{row.name}</p><span className={`mt-1 inline-flex rounded-full px-2.5 py-1 text-[10px] font-semibold capitalize ${row.status==='active'?'bg-green-50 text-green-700':'bg-gray-100 text-gray-600'}`}>{row.status}</span></div><div className="flex gap-2"><button onClick={()=>edit(row)} className="inline-flex items-center gap-2 rounded-lg bg-gray-50 px-3 py-2 text-xs font-semibold"><Pencil size={14}/> Edit</button><button onClick={()=>void remove(row.id)} className="inline-flex items-center gap-2 rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-700"><Trash2 size={14}/> Delete</button></div></div>)}</div>}</div></div>}
